### ISSUE TITLE
Editable database engine string

### ISSUE THREAD

**Issue by mcovalt** [girder/django-composed-configuration#161]
The `DATABASES[db_name]['ENGINE']` setting defaults to `'django.db.backends.postgresql'`, but I need it to equal `'django.contrib.gis.db.backends.postgis'` for use with [GeoDjango](https://docs.djangoproject.com/en/4.0/ref/contrib/gis/).

Is there a clean way to do this? [My current fix is to rewrite the whole value in our settings.py](https://github.com/atlascope/atlascope/blob/20fcd070117a84db9a7f801b226d476280033a35/atlascope/settings.py#L29-L39).

**Comment by brianhelba** [comment]
`mutate_configuration` runs before class-level `Values` have been fully evaluated, so it provides an opportunity to modify those objects. Here, `DATABASES` is an instance of [`DatabaseURLValue`](https://github.com/jazzband/django-configurations/blob/c3b5e8627b82007f73a63283553d4b1cb831320d/configurations/values.py#L456), which inherits [`CastingMixin`](https://github.com/jazzband/django-configurations/blob/c3b5e8627b82007f73a63283553d4b1cb831320d/configurations/values.py#L145). You *could* do something like:
```
class AtlascopeMixin:
    @staticmethod
    def mutate_configuration(configuration: ComposedConfiguration) -> None:
        configuration.DATABASES._params['engine'] = 'django.contrib.gis.db.backends.postgis'
```
but that's getting pretty delicate.

Overriding `DATABASES` as you've done may be the most maintainable solution, IMO. Inevitably, downstream customization may need to repeat something from upstream, but that may just be a necessary price.

Certainly, the best balance between DRY and decoupling is a matter of judgement.
