### ISSUE TITLE
Add memcached config for different Heroku plugins

### ISSUE THREAD

**Issue by banesullivan** [girder/django-composed-configuration#163]
In RGD, we created an [`MemachedMixin`](https://github.com/ResonantGeoData/ResonantGeoData/blob/0ed6fbeddbfc074c5e2b0e636288a5bbdc2cb790/django-rgd/rgd/configuration/configuration.py#L44) class for setting up the Django cache to use memcached. Additionally, we use this configuration with large-image.

A challenge is that each of the Memcached plugins on Heroku all use different environment variable names. [memcachedcloud](https://elements.heroku.com/addons/memcachedcloud) uses:

![Screen Shot 2022-01-18 at 9 18 07 PM](https://user-images.githubusercontent.com/22067021/150063583-bc9d2bc2-5632-4025-a23c-72a38f0f3acc.png)

I think it'd be useful to have this `MemachedMixin` included in `django-composed-configuration` and also have a few variations for commonly used Memcached providers, e.g: `MemachedCloudMixin`, `MemcachierMixin`, etc.

**Comment by banesullivan** [comment]
Actually. I'm having trouble getting that mixin to work on Heroku. The `post_setup` properly sets `CACHES`, but it is reset to the default somewhere along the way...

**Comment by brianhelba** [comment]
I don't foresee that composed-configuration will ever enable Memcached. If we decide that caching support needs to be part of a default project stack, I think Redis is the more modern and better choice.

However, it's totally possible for a project ecosystem like ResonantGeoData to publish their own `MemachedMixin` for projects which wish to use it.

As a matter of library scope, django-composed-configuration provides a single (extensible) configuration, but can't serve many more advanced use cases. Additionally, as this library has evolved, I've become even more pessimistic that the mixins will be truly re-composable (i.e. mix and match your own). Mostly, the separate classes provide logical encapsulation for internal development sanity. Everything beyond that (i.e. downstream importing and re-composing the mixins) is probably quite unstable.

**Comment by banesullivan** [comment]
> If we decide that caching support needs to be part of a default project stack, I think Redis is the more modern and better choice.

+1 for redis

> However, it's totally possible for a project ecosystem like ResonantGeoData to publish their own MemachedMixin for projects which wish to use it.

Fair enough (and we are), just trying to backport things that I think make sense our could be used in more Girder4 projects. Until large image supports redis (likely an easy change), having Memcached is needed. This issue and the response in #141 has me wondering if `django-composed-configuration` is gearing itself towards the broader django community or Kitware's Girder4 ecosystem? If the latter, things like this (or redis) and #141 seem within scope to me - perhaps this is better suited for an offline discussion.

> Additionally, as this library has evolved, I've become even more pessimistic that the mixins will be truly re-composable (i.e. mix and match your own). ... is probably quite unstable.

😞 ... I've been pretty optimistic about this being a mix-and-match set of configurations, so that's a bit disheartening to a degree
